version: '3.7'

networks:
  nginxnetwork:
    attachable: true
    internal: true
    name: nginxnetwork

volumes:
  reverseproxy_letsencrypt:
  reverseproxy_nginx_conf:

services:
  reverseproxy:
    image: huguesmcd/reverseproxy
    environment:
      - "STAGING=true"
      - "EMAIL=email@gmail.com"
    ports:
        - "80:80"
        - "443:443"
    networks:
      - nginxnetwork
    volumes:
      - reverseproxy_nginx_conf:/etc/nginx/conf.d/
      - reverseproxy_letsencrypt:/etc/letsencrypt

